spring:
  application:
    name: discovery

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: false
    fetch-registry: false
    instance-info-replication-interval-seconds: 3
  server:
    enable-self-preservation: true
    eviction-interval-timer-in-ms: 5000

server:
  port: 8761